spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drink-sys?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pwofmysql
