spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drink-sys?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  appId: "wxddf5165783eb9495"
  secret: "e912ee5abfa8ecd1007b25a338b42b60"